### ISSUE TITLE
realizar diseño de reporte de todos los estudiantes

### ISSUE THREAD

**Issue by Cristian-Barajas09** [Cristian-Barajas09/ProyectoUni#17]
se realizara un diseño de reporte para los estudiantes en html/css/js puede ser una lista o una tabla. ojo solo quiero el diseño no completar los campos yo me encargo de renderizar dichos campos.

el css y el js deben ir en el mismo html (se que es horrible pero es lo que hay)

el archivo debe ir en la carpeta templates

**Comment by Maro2001v** [comment]
con diseño es específicamente visual? o sea no le hago nada funcional con el js?

**Comment by Cristian-Barajas09** [comment]
![chad](https://github.com/Cristian-Barajas09/ProyectoUni/assets/110863445/435c3005-85d9-45bd-b087-752cd5495500)
